---

- name: Network Getting Started First Playbook
  hosts: all
  gather_facts: false
  tasks:

    - name: Display the config
      debug:
        msg: "Hellow World!"
        
    - name: Get config for IOS devices
      cisco.ios.ios_facts:
        gather_subset: all

    - name: Display the config
      debug:
        msg: "The hostname is {{ ansible_net_hostname }} and the OS is {{ ansible_net_version }}"
