---

- name: Network Getting Started First Playbook
  hosts: all
  gather_facts: false
  ansible_connection: ansible.netcommon.network_cli
  tasks:

    - name: Display the config
      debug:
        msg: "Hellow World!"
